### ISSUE TITLE
Fetch data asyncronously?

### ISSUE THREAD

**Issue by phobson** [Geosyntec/cloudside#20]
from https://async-generator.readthedocs.io/en/latest/reference.html#async-generators:

```python
async def load_json_lines(stream_reader):
    async for line in stream_reader:
        yield json.loads(line)
```

**Comment by austinorr** [comment]
closing this issue. `async-generator` is abandoned.

including async is a pretty good idea for a massive fetching library like this, but let's open a fresh issue to discuss. modern solutions include `aiohttp` and/or `asyncio.to_thread()`.
